### ISSUE TITLE
Confusion about PLIP analysis

### ISSUE THREAD

**Issue by lbwfff** [twopin/CAMP#11]
Hi, twopin
I have some confusion about PLIP analysis. First of all, you did not provide Data_construction.txt. I'm not sure what the result.txt file is. Is it the XXX_protonated.pdb file?
Then I need to provide analysis files of different chains of pdb_id, such as 6dub_e_result.txt and 6dub_f_result.txt, but I found that I cannot specify a specific chain when downloading the PDB file. Is there a problem with my download method or the analysis method? It would be very helpful if you can provide the code of PLIP if it is convenient.
Thank,
LeeLee

**Comment by lbwfff** [comment]
Sorry for asking so many questions, but this is really important to me. If I don’t want to train but directly use the already built model, can I start directly from STEP3? Can the provided code support me to convert the peptide sequence and protein sequence of interest into files (protein_ss, peptide_ss)?

**Comment by twopin** [comment]
When downloading the PDB file, you only need to download the complete complex files. And then when using PLIP to analyze two specific chains, you can specify the chain IDs using command from https://github.com/pharmai/plip.

**Comment by twopin** [comment]
To generate SS features, first you need to get files like "seq_data.out.ss" by SCRATCH-1D (usually installed and run on Linux servers with fasta file as input), then using the codes from step3_generate_features.py (line 99-142) to process the SS feature. Finally, using the  codes in preprocess_features.py the convert the SS features into feature dictionaries.
