### ISSUE TITLE
How to download the file uniprot2seq from UniProt Website

### ISSUE THREAD

**Issue by milkboylyf** [twopin/CAMP#14]
Hi, in the function **load_uni_seq** in **data_prepare/step1_pdb_process.py**, it requires an input called **uniprot2seq_file**, uniprot2seq from UniProt Website (a tab separated file with fields including Uniprot_id,Uniprot Sequence,Protein_name,Protein_families), how to download this file from UniProt Website and can you provide a download link for this file. Thanks.

**Comment by milkboylyf** [comment]
Hi, twopin. I also get trouble in the file format called **crawl_results.csv** in the module data_prepare/query-mapping.py, can you provide template data for this file. Thanks.

**Comment by twopin** [comment]
Hi, you can download the sequence files from : https://www.uniprot.org/downloads.

**Comment by twopin** [comment]
Sorry I did not save the intermediate file but you can use your own data. The important part of the script begins from line 49. You can adjust the script according to your own data format.

**Comment by milkboylyf** [comment]
> Hi, you can download the sequence files from : https://www.uniprot.org/downloads.

Hi, twopin, thanks for your reply.  When I visit the link **https://www.uniprot.org/downloads**, it represents as follows and which link needs to be clicked so as to get  the file **uniprot2seq_file**.  After download the file,  should I further clean the data  to get the columns **Uniprot_id,Uniprot Sequence,Protein_name,Protein_families**.
![image](https://user-images.githubusercontent.com/40199966/149688308-5cd1980f-e5e9-44ed-ac91-627cbbbda7ed.png)

![image](https://user-images.githubusercontent.com/40199966/149688752-acffbbb2-e3de-4b75-b067-0fd60cfe136a.png)

**Comment by zhouruikang1024** [comment]
> Hi, twopin. I also get trouble in the file format called **crawl_results.csv** in the module data_prepare/query-mapping.py, can you provide template data for this file. Thanks.

Hi, I also don't know the crawl_results.csv format. Have you solved the crawl_results.csv format problem? Could you please provide this file or a sample data format?

**Comment by rocke2020** [comment]
Dear twopin, could you share us exactly how to get the uniprot2seq_file from https://www.uniprot.org/help/downloads.
what's final link inside the  https://www.uniprot.org/help/downloads
thanks in advance!!

**Comment by rocke2020** [comment]
> > Hi, you can download the sequence files from : https://www.uniprot.org/downloads.
> 
> Hi, twopin, thanks for your reply. When I visit the link **https://www.uniprot.org/downloads**, it represents as follows and which link needs to be clicked so as to get the file **uniprot2seq_file**. After download the file, should I further clean the data to get the columns **Uniprot_id,Uniprot Sequence,Protein_name,Protein_families**. ![image](https://user-images.githubusercontent.com/40199966/149688308-5cd1980f-e5e9-44ed-ac91-627cbbbda7ed.png)
> 
> ![image](https://user-images.githubusercontent.com/40199966/149688752-acffbbb2-e3de-4b75-b067-0fd60cfe136a.png)

Do you finally get the download link? If so, could share with us? thanks!!

**Comment by Yiqiu-Zhang** [comment]
I did not find any file that fits the description, but I find a file which contains the Uniport ID and the proteins families
https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/docs/similar

**Comment by twopin** [comment]
I've uploaded the exact data I downloaded when doing this project. Actually the file was directly downloaded from UniProt when just selecting all the fasta sequence file. You guys can directly use mine or downloaded the latest version.

**Comment by twopin** [comment]
> Hi, twopin. I also get trouble in the file format called **crawl_results.csv** in the module data_prepare/query-mapping.py, can you provide template data for this file. Thanks.

This file is the output file using the crawling script.

**Comment by twopin** [comment]
The UniProt website has updated since 2020 and here is how to download now:
![image](https://user-images.githubusercontent.com/22184602/223761822-01cb236b-9d0d-469b-9dd7-56f30bc8fcce.png)
![image](https://user-images.githubusercontent.com/22184602/223761859-44e23b0d-4a7d-4d35-9f44-db7482ac5931.png)

**Comment by rocke2020** [comment]
@twopin thanks for your reply.
Do you get the Protein_families from
https://www.uniprot.org/uniprotkb?query=reviewed:false
or https://www.uniprot.org/help/downloads

I think the downloaded fasta file only have ProteinName which is not its protein family name, yes?
I think we make this issue to ask help to you on where get the protein family.

>db|UniqueIdentifier|EntryName ProteinName OS=OrganismName OX=OrganismIdentifier [GN=GeneName ]PE=ProteinExistence SV=SequenceVersion

> The UniProt website has updated since 2020 and here is how to download now: ![image](https://user-images.githubusercontent.com/22184602/223761822-01cb236b-9d0d-469b-9dd7-56f30bc8fcce.png) ![image](https://user-images.githubusercontent.com/22184602/223761859-44e23b0d-4a7d-4d35-9f44-db7482ac5931.png)

**Comment by twopin** [comment]
> @twopin thanks for your reply. Do you get the Protein_families from https://www.uniprot.org/uniprotkb?query=reviewed:false or https://www.uniprot.org/help/downloads
> 
> I think the downloaded fasta file only have ProteinName which is not its protein family name, yes? I think we make this issue to ask help to you on where get the protein family with uniprot id. Or do you treat ProteinName as protein faimily name, if there is "MHC" in the ProteinName, filter out it? We find protein family name in the link below. https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/docs/similar
> 
> > db|UniqueIdentifier|EntryName **ProteinName** OS=OrganismName OX=OrganismIdentifier [GN=GeneName ]PE=ProteinExistence SV=SequenceVersion
> 
> BTW, could you share: this paper use the review uniprot sp sequences or the unreviewed sequences? your picture is the unreviewed sequences, while you upload and codes seems to use review uniprot sp sequences. thanks for your share!

please see my reply below.

**Comment by rocke2020** [comment]
> Oh actually you don't need the protein family information for CAMP but if you do need that for downstreaming analysis, you can customize the column information on UniProt when downloading the sequence. 

@twopin , in your paper and your shared codes, you filtered protein sequence which belong to MHC protein family. (●'◡'●)
