### ISSUE TITLE
About DrugBank Data

### ISSUE THREAD

**Issue by milkboylyf** [twopin/CAMP#16]
Hi, twopin. I wonder if you use drugbank dataset for training and what data pre-processing did you use ?

**Comment by Ruheng-W** [comment]
I also encounters the same question here and hope the author can give the quick reply.

**Comment by twopin** [comment]
Hi, thank you for your interests in our work. For the DrugBank data, you need to select all drug-target pairs whose  categories  belong to "peptides category "(see Supplementary Note 10 for detail information).
