### ISSUE TITLE
demo data: example output files

### ISSUE THREAD

**Issue by dlemas** [twopin/CAMP#19]
We have worked to get CAMP running on our local cluster, and I have successfully run `predict_CAMP.py` on the `example_data.csv`. This produced 3 npy files and I could not find documentation explaining the output and interpretation of results. @twopin-can you push the example data output files to the repo and provide more documentation on how to interpret the CAMP output?

**Comment by twopin** [comment]
Actually the predicted interacting score is stored in 'pred_label', and the corresponding encoded AA sequences can be found in ‘pep_sequence’  and 'prot_sequence'.

**Comment by dlemas** [comment]
Where are these files located? I am specifically referring to files located in: ~/CAMP/example_prediction/

- bs_pred_test.npy
- bs_test_peptide.npy
- bs_test_protein.npy
