### ISSUE TITLE
Questions about creating "query_peptide.fasta" and "target_peptide.fasta"

### ISSUE THREAD

**Issue by AnthonyYao7** [twopin/CAMP#27]
Hello!

I am working on running step2_pepbdb_pep_bindingsites.py but I am having a few problems with the inputs. 
I have successfully run crawl.py and have crawl_results.csv. However, I am confused about how to generate query_peptide.fasta and target_peptide.fasta. I understand that odd numbered lines should have information about the peptide and even numbered lines should have the sequence. What information should be included for each peptide?

Also, am I correct in saying that crawl.py should be run first, followed by query_mapping.py, then pyssw.py, then target_mapping.py?

Finally, is this the correct link to download pepbdb database: http://huanglab.phys.hust.edu.cn/pepbdb/db/download/  

Thank you for your help!

**Comment by twopin** [comment]
You can use try some python cmds to convert sequence files into fasta (like try to identify the sequence name by starting with '>' and the next line should be the aa sequence.

**Comment by a30221274** [comment]
Hello

I've encountered a similar issue after running pyssw.py. May I ask how you managed to resolve it?
