### ISSUE TITLE
We couldn't run program

### ISSUE THREAD

**Issue by denizozcivi** [twopin/CAMP#34]
Hi Dear,

Firstly, many thanks for the application. We couldn't run this application using Visual code studio. We are facing a python version problem. Do you have an updated version of this code from python 2.7 to 3

Or what should we do to run this application? 

Regards,
Deniz

**Comment by twopin** [comment]
Sorry for the inconvenient. As mentioned before, we are preparing a pytorch+python3 version model ckpt for better inference. Meanwhile, you can still use the python2 version (conda install a python2 environment) to directly predict using the B5 model file.

**Comment by denizozcivi** [comment]
I am still facing problem to run this application. I am receiving some files are missing. For example, I can't find datafile. I am not professional code side maybe I am missing some of the steps. If we can quick chat to understand this application, it might perfect for me. Because I am planning to use your code in my thesis. But I can't get any output and I can't make any presentation about this. denizozcivi@gmail.com and I am happy to talk on the phone if you have time to small help.

Best Regards,
Deniz

**Comment by twopin** [comment]
Sure. My email is twopinlei@hotmail.com and if you need some help we can schedule a zoom meeting or something like that. I can quickly introduce the workflow. There are indeed some filenames you need to change with your own data or intermediate feature files. And I think you need to have basic python knowledge to manipulate your data format.
