### ISSUE TITLE
Where is the directory './peptide_results'?

### ISSUE THREAD

**Issue by liang98** [twopin/CAMP#4]
Hi, when I try to run step1_pdb_process, I can't find the directory './peptide_results'. Could you tell me how to find it?

**Comment by twopin** [comment]
Hi,
First you need to use PLIP (https://github.com/pharmai/plip) to analyze the complex structures (step 0) to obtain the binding residue labels. You need to place the PLIP results in a folder named 'peptide_results' and then run the codes in step1.

**Comment by twopin** [comment]
I also notice that PLIP has an updated version, which you can obtain the analyzed results of published PDB complexes in seconds.
