### ISSUE TITLE
"query_peptide.fasta" and "target_peptide.fasta"

### ISSUE THREAD

**Issue by a30221274** [twopin/CAMP#42]
Hello

I've encountered a similar issue after running pyssw.py. May I ask how you managed to resolve it?

_Originally posted by @a30221274 in https://github.com/twopin/CAMP/issues/27#issuecomment-2016721021_

**Comment by a30221274** [comment]
Hi, thank you for your work

Could you please inform me from which two files the "query_peptide.fasta" file and the "target_peptide.fasta" file were derived?

**Comment by twopin** [comment]
Hi, this is the peptide sequences or protein sequences you want to align.
