### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by nhowla** [twopin/CAMP#5]
Hello All,
I read your paper, and I enjoy reading this paper. I am fairly new in coding if you could provide the model src instead/along with CAMP.h5 that will be great. Thank you so much

**Comment by twopin** [comment]
Hi,
You can use the script 'predict_CAMP.py'  to call the CAMP.h5 model file and make inference. For feature generation, you can follow the manual in README and use 'feature_preprocessing.py' to process the features.
