### ISSUE TITLE
 predict with example code use the test data

### ISSUE THREAD

**Issue by leavdragon** [twopin/CAMP#7]
Hi, I predict with example code and use the test data with the command 'python -u predict_CAMP.py'.
However, the following error is indicated.
‘File "predict_CAMP.py", line 178, in <module>
    X_pep, X_p, X_SS_pep, X_SS_p, X_2_pep, X_2_p, X_dense_pep, X_dense_p, pep_sequence, prot_sequence = load_example(model_mode)
File "predict_CAMP.py", line 82, in load_example
    protein_feature_dict = pickle.load(f)
TypeError: a bytes-like object is required, not 'str'  ’

Am I using the features in ‘example_data_feature’ incorrectly, or is there a problem with the file format somewhere? I look forward to and appreciate your answer.

**Comment by twopin** [comment]
Hi, I think the reason might be that the feature dict you want to load in not pickled under the same version of python.  In Python 3 you need to specifically call either 'rb' or 'wb'.

**Comment by poloarol** [comment]
Hello, just ran into the same problem. Which version of pickle was used to serialize the files (@twopin )? Also how did you solve the issue @leavdragon
