### ISSUE TITLE
Problems in the STEP 2: Generate labels of peptide binding residues 

### ISSUE THREAD

**Issue by Alyssa-vv** [twopin/CAMP#8]
Anyone can help with the step2?

How to generate the file: './pdb/peptide-mapping.txt'?
I can not find the "query_mapping.py" and "target_mapping.py ".

"#python query_mapping.py #to get peptide sequence vectors (the output is "peptide-mapping.txt ")"
"#python target_mapping.py #to get target sequence vector"

Thank you!

**Comment by twopin** [comment]
Hi, Thank you for your interests in our work. I uploaded these two scripts now.

**Comment by liuzhelz** [comment]
> Anyone can help with the step2?
> 
> How to generate the file: './pdb/peptide-mapping.txt'? I can not find the "query_mapping.py" and "target_mapping.py ".
> 
> "#python query_mapping.py #to get peptide sequence vectors (the output is "peptide-mapping.txt ")" "#python target_mapping.py #to get target sequence vector"
> 
> Thank you!

   Hi, @twopin  @Alyssa-vv , i have some trouble in dada_prepare/step_2, i can not find crawl_results.csv in the module data_prepare/query-mapping.py, could you give me some help?

Thank you!

**Comment by twopin** [comment]
Sorry I did not save the intermediate file but you can use your own data. The important part of the script begins from line 49. You can adjust the script according to your own data format.

**Comment by liuzhelz** [comment]
> Sorry I did not save the intermediate file but you can use your own data. The important part of the script begins from line 49. You can adjust the script according to your own data format.

```
csvfile=open('crawl_results.csv','r')
reader=csv.reader(csvfile)
residue_dict={}
seq_dict={}
    
for item in reader:
    if reader.line_num==1:  
        continue
    qid=item[0]
    querys.append(qid)
    pep_index=item[1].split(': ') #prot_index=item[3].split(': ')
    residue_dict[item[0]]=pep_index[1]
    seq_dict[item[0]]=item[2].split(': ')[1]#seq_dict[item[0]]=item[4].split(': ')[1]
```
  Hi,@twopin  Thank you for your reply. Now I have 'interacted peptide protein pairs from PDB',  'PLIP_results', 'pdbid_ all_ fasta' and 'pdb_ pep_ Chain' files generated from step_1 and PepBDB data set mentioned in the paper, but I don't know what data should be used to generate the 'crawl_results.csv' file？What is the function of this file.

Thank you!

**Comment by NingNing-C** [comment]
Hi @liuzhelz, 

I also have the same problem, did you solve it? 

Many thanks!

**Comment by twopin** [comment]
Hi @liuzhelz @NingNing-C  Sorry that I didn't reply earlier. I've uploaded a script called crawl.py to generate such results.
