### ISSUE TITLE
SSpro claculation for peptide

### ISSUE THREAD

**Issue by zjujdj** [twopin/CAMP#9]
hello,
the SSpro program in the SCRATCH-1D suite was needed the protein sequence is at least 30 amino acids in length, but many peptides in the provied sample data are less than that number  in length, i wonder konw how to deal with those peptides using SSpro program.
thx!

**Comment by twopin** [comment]
Hi,
What's your version of SSPro? The version I used to calculate the secondary structures can solve cases that have lengths shorter than 30.  The version information is as follow:

Author(s) :  Christophe Magnan (cmagnan@ics.uci.edu)
Copyright :  Institute for Genomics and Bioinformatics
             University of California, Irvine
Modified  :  2018/11/24

====================================================================================================
                                         Method Description
====================================================================================================

SCRATCH-1D is a suite of one-dimensional predictors included in the long-established and widely used
SCRATCH suite of predictors developed by the Institute for Genomics and Bioinformatics (IGB) of the
University of California, Irvine (UCI) : http://scratch.proteomics.ics.uci.edu

SCRATCH-1D currently includes the following predictors and tools:

 - SSpro      Release 5.2  Protein secondary structure prediction (3-class)
 - SSpro8     Release 5.2  Protein secondary structure prediction (8-class)
 ...
====================================================================================================
                                           Release Notes
====================================================================================================

Version 1.2 (2018)

Author      :  Christophe Magnan
Description :  update of the package databases
Comments    :  PROFILpro protein database UNIREF50 updated
               HOMOLpro template database pdb_full updated
